apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-deployment
  labels:
    app: parser
spec:
  replicas: 4
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: mlodyajdza/parser:latest
          ports:
          - containerPort: 8095
            protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pargres-ingress
  namespace: producation
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: parser
            port:
              number: 8095
