annotations:
  category: Infrastructure

apiVersion: v2

dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x

description: NGINX Ingress Controller is an Ingress controller that manages external
  access to HTTP services in a Kubernetes cluster using NGINX.

icon: https://bitnami.com/assets/stacks/nginx-ingress-controller/img/nginx-ingress-controller-stack-220x234.png

kubeVersion: '>= 1.20.0-0'

name: nginx-ingress-controller

version: 9.3.19
